# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15MKp6IrIFIs58aPVgW9kcYc-2uX1LbSu
"""

"""
EMI Predict AI - Streamlit App
--------------------------------
Run with:  streamlit run app.py

Before running, make sure these 5 files are in the same folder:
    - xgb_classifier.pkl
    - xgb_regressor.pkl
    - scaler.pkl
    - label_encoder.pkl
    - feature_columns.pkl
(They are produced by save_artifacts.py from your notebook.)
"""

import joblib
import numpy as np
import pandas as pd
import streamlit as st

# ------------------------------------------------------------
# 1. Load the trained artifacts (cached so it only loads once)
# ------------------------------------------------------------
@st.cache_resource
def load_artifacts():
    clf     = joblib.load("xgb_classifier.pkl")
    reg     = joblib.load("xgb_regressor.pkl")
    scaler  = joblib.load("scaler.pkl")
    le      = joblib.load("label_encoder.pkl")
    feat_cols = joblib.load("feature_columns.pkl")
    return clf, reg, scaler, le, feat_cols

clf, reg, scaler, le, FEATURE_COLS = load_artifacts()

# The SAME numeric columns used in the notebook for StandardScaler
NUM_COLS = [
    "age", "monthly_salary", "years_of_employment", "monthly_rent",
    "family_size", "dependents", "school_fees", "college_fees",
    "travel_expenses", "groceries_utilities", "other_monthly_expenses",
    "existing_loans", "current_emi_amount", "credit_score",
    "bank_balance", "emergency_fund", "requested_amount", "requested_tenure",
    "total_expenses", "disposable_income", "debt_to_income",
    "expense_to_income", "savings_ratio", "requested_emi_estimate",
    "requested_emi_to_income",
]

# ------------------------------------------------------------
# 2. Page config + header
# ------------------------------------------------------------
st.set_page_config(page_title="EMI Predict AI", page_icon="money", layout="wide")

st.title("EMI Predict AI")
st.caption("Predicts loan eligibility and the maximum monthly EMI an applicant can afford.")

# ------------------------------------------------------------
# 3. Input form (sidebar)
# ------------------------------------------------------------
st.sidebar.header("Applicant details")

with st.sidebar.form("applicant_form"):
    st.subheader("Personal")
    age            = st.number_input("Age", 18, 75, 35)
    gender         = st.selectbox("Gender", ["Male", "Female"])
    marital_status = st.selectbox("Marital status", ["Single", "Married"])
    education      = st.selectbox("Education",
                                  ["High School", "Graduate", "Post Graduate", "Professional"])
    family_size    = st.number_input("Family size", 1, 15, 4)
    dependents     = st.number_input("Dependents", 0, 10, 1)

    st.subheader("Employment")
    employment_type     = st.selectbox("Employment type",
                                       ["Government", "Private", "Self-employed"])
    company_type        = st.selectbox("Company type",
                                       ["Government", "Large", "SME", "Startup"])
    years_of_employment = st.number_input("Years of employment", 0, 45, 5)
    monthly_salary      = st.number_input("Monthly salary", 0, 1_000_000, 50_000, step=1000)

    st.subheader("Housing & expenses")
    house_type             = st.selectbox("House type", ["Own", "Rented", "Family"])
    monthly_rent           = st.number_input("Monthly rent", 0, 200_000, 0, step=500)
    school_fees            = st.number_input("School fees", 0, 100_000, 0, step=500)
    college_fees           = st.number_input("College fees", 0, 100_000, 0, step=500)
    travel_expenses        = st.number_input("Travel expenses", 0, 50_000, 5_000, step=500)
    groceries_utilities    = st.number_input("Groceries + utilities", 0, 100_000, 15_000, step=500)
    other_monthly_expenses = st.number_input("Other monthly expenses", 0, 100_000, 5_000, step=500)

    st.subheader("Financial")
    existing_loans     = st.selectbox("Existing loans?", [0, 1])
    current_emi_amount = st.number_input("Current EMI amount", 0, 200_000, 0, step=500)
    credit_score       = st.slider("Credit score", 300, 850, 650)
    bank_balance       = st.number_input("Bank balance", 0, 10_000_000, 200_000, step=1000)
    emergency_fund     = st.number_input("Emergency fund", 0, 5_000_000, 50_000, step=1000)

    st.subheader("Loan request")
    emi_scenario     = st.selectbox("EMI scenario",
                                    ["E-commerce", "Education", "Home Appliances",
                                     "Personal Loan", "Vehicle"])
    requested_amount = st.number_input("Requested amount", 10_000, 2_000_000, 200_000, step=1000)
    requested_tenure = st.slider("Requested tenure (months)", 3, 84, 24)

    submitted = st.form_submit_button("Predict", use_container_width=True)


# ------------------------------------------------------------
# 4. Preprocessing - must match the notebook EXACTLY
# ------------------------------------------------------------
def preprocess(user_input: dict) -> pd.DataFrame:
    """Turn raw form input into a single-row DataFrame aligned to FEATURE_COLS."""
    df = pd.DataFrame([user_input])

    # --- Feature engineering (same 7 features as notebook) ---
    df["total_expenses"] = (df["monthly_rent"] + df["school_fees"] + df["college_fees"]
                            + df["travel_expenses"] + df["groceries_utilities"]
                            + df["other_monthly_expenses"] + df["current_emi_amount"])
    df["disposable_income"]       = df["monthly_salary"] - df["total_expenses"]
    df["debt_to_income"]          = df["current_emi_amount"] / df["monthly_salary"]
    df["expense_to_income"]       = df["total_expenses"] / df["monthly_salary"]
    df["savings_ratio"]           = df["bank_balance"] / (df["monthly_salary"] * 12)
    df["requested_emi_estimate"]  = df["requested_amount"] / df["requested_tenure"]
    df["requested_emi_to_income"] = df["requested_emi_estimate"] / df["monthly_salary"]

    # --- One-hot encoding (same cols + drop_first=True as notebook) ---
    cat_cols = ["gender", "marital_status", "education", "employment_type",
                "company_type", "house_type", "emi_scenario"]
    df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

    # Reindex to the exact column order used during training.
    # Any missing dummy column is filled with False (0).
    df = df.reindex(columns=FEATURE_COLS, fill_value=0)

    # --- Scale the numeric columns with the trained scaler ---
    df[NUM_COLS] = scaler.transform(df[NUM_COLS])

    return df


# ------------------------------------------------------------
# 5. Prediction + results
# ------------------------------------------------------------
if submitted:
    user_input = dict(
        age=age, gender=gender, marital_status=marital_status, education=education,
        monthly_salary=monthly_salary, employment_type=employment_type,
        years_of_employment=years_of_employment, company_type=company_type,
        house_type=house_type, monthly_rent=monthly_rent, family_size=family_size,
        dependents=dependents, school_fees=school_fees, college_fees=college_fees,
        travel_expenses=travel_expenses, groceries_utilities=groceries_utilities,
        other_monthly_expenses=other_monthly_expenses, existing_loans=existing_loans,
        current_emi_amount=current_emi_amount, credit_score=credit_score,
        bank_balance=bank_balance, emergency_fund=emergency_fund,
        emi_scenario=emi_scenario, requested_amount=requested_amount,
        requested_tenure=requested_tenure,
    )

    X_new = preprocess(user_input)

    # Classification
    pred_enc   = clf.predict(X_new)[0]
    pred_class = le.inverse_transform([pred_enc])[0]
    proba      = clf.predict_proba(X_new)[0]

    # Regression
    pred_max_emi = float(reg.predict(X_new)[0])

    # --- Show results ---
    st.subheader("Prediction results")

    col1, col2 = st.columns(2)
    with col1:
        if pred_class == "Eligible":
            st.success(f"Eligibility: **{pred_class}**")
        elif pred_class == "High_Risk":
            st.warning(f"Eligibility: **{pred_class}**")
        else:
            st.error(f"Eligibility: **{pred_class}**")

    with col2:
        st.metric("Predicted max monthly EMI", f"{pred_max_emi:,.0f}")

    st.write("### Class probabilities")
    proba_df = pd.DataFrame({"class": le.classes_, "probability": proba})
    st.bar_chart(proba_df.set_index("class"))

    with st.expander("See input sent to the model"):
        st.dataframe(X_new.T.rename(columns={X_new.index[0]: "value"}))
else:
    st.info("Fill out the applicant form in the sidebar and click **Predict**.")